# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

name: Documentation - New Documentation Request
description: Request additions to documentation
title: "[DOC]: "
labels: ["doc"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to improve our documentation!

  - type: dropdown
    id: criticality
    attributes:
      label: How would you describe the priority of this documentation request
      options:
        - Critical (currently preventing usage)
        - High
        - Medium
        - Low (would be nice)
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Describe the future/missing documentation
      placeholder: A code snippet mentions function foo(args) but I cannot find any documentation on it.
    validations:
      required: true

  - type: textarea
    id: search_locs
    attributes:
      label: Where have you looked?
      placeholder: |
       https://github.com/NVIDIA-Omniverse/mjc-usd-converter/blob/main/README.md

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/NVIDIA-Omniverse/mjc-usd-converter/blob/HEAD/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow mjc-usd-converter Code of Conduct
          required: true
        - label: I have searched the [open bugs](https://github.com/NVIDIA-Omniverse/mjc-usd-converter/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates
          required: true
