include:
  - project: 'omniverse/sectools/vault'
    file: 'templates/v3/linux/artifactory.gitlab-ci.yml'
  - project: 'omniverse/devplat/gitlab/templates/runners'
    file: 'modules/include.yml'
    ref: v2_latest
  - project: 'omniverse/devplat/gitlab/templates/common/compliance'
    file: 'modules/omniverse-repo-compliance.gitlab-ci.yml'
    ref: v1_latest

stages:
  - check
  - build
  - test
  - deploy

workflow:
  rules:
    - if: $CI_COMMIT_TAG # Run for tagged releases
    - if: $CI_COMMIT_REF_PROTECTED == "true" # Run for main and release/* maintenance branches
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Run for MRs

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  OSEC_NSPECT_ID: NSPECT-DRJJ-1IL9
  OSEC_SONARQUBE_ENABLED: true
  OSEC_OMNI_SANITIZER_ENABLED: true
  OSEC_CHECKMARX_ENABLED: false
  OSEC_OMNI_PULSE_ENABLED: false

cache:
  paths:
    - .pip-cache
    - .venv

.default_job:
  timeout: 10 minutes
  interruptible: true
  # Only retry on Gitlab failures (not on script failures for example)
  retry:
    max: 2
    when:
      - api_failure
      - runner_system_failure
      - stuck_or_timeout_failure
      - scheduler_failure
      - unknown_failure
  artifacts:
    when: always
    expire_in: 2 weeks

.osec:stage_base:
  stage: check # setup all osec jobs as checks

check_code_format:
  extends: [.default_job]
  stage: check
  script:
    - poetry install
    - poetry run poe lint

.build_base:
  extends: [.default_job]
  stage: build
  needs: [] # do not wait for checks
  script:
    - poetry install
    - poetry build
  artifacts:
    paths:
      - dist/

build_linux:
  extends: [.build_base, .omni_nvks_small_runner_with_docker]

build_windows:
  extends: [.build_base, .runner-build-windows-x86_64]

.test_base:
  extends: [.default_job]
  stage: test
  script:
    - poetry install
    - poetry run poe test

test_linux:
  extends: [.test_base, .omni_nvks_micro_runner]

test_windows:
  extends: [.test_base, .runner-build-windows-x86_64]

deploy:
  extends: [.default_job, .omni_nvks_micro_runner, .osec:vault:v3:prod_token_job]
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: always
    - when: manual
  before_script:
    - !reference [.osec:vault:v3:linux, artifactory:perform_vault_requests]
  script:
    - poetry publish --repository https://REDACTED -u $ARTIFACTORY_USERNAME -p $ARTIFACTORY_KEY --verbose dist/*.whl
